site_name: nwbmatic
nav:  
  - Overview: index.md
  - Tutorials: 
    - Loading neurosuite-optitrack: nwbmatic-neurosuite-optitrack.md
    - Custom IO: nwbmatic-custom-io.md
    # - Gallery: generated/gallery
  - Modules:
    - Miscellaneous: io.md
    - Basic IO: io.loader.md
    - Neurosuite: io.neurosuite.md
    - Phy: io.phy.md
    - CNMF-E: io.cnmfe.md
    - Suite2p: io.suite2p.md
  - Contributing: CONTRIBUTING.md
  - Authors: AUTHORS.md  
theme:
  name: 'material'  
  # highlightjs: true
  # hljs_style: github
  # hljs_languages:
  #   - python
  palette:
    primary: 'grey'
  # features:
  #   - navigation.tabs
repo_url: https://github.com/pynapple-org/nwbmatic
plugins:
  - mkdocstrings
  # - gallery:
  #      examples_dirs: docs/examples          # path to your example scripts
  #      gallery_dirs: docs/generated/gallery  # where to save generated gallery
  #     # ... (other options)
  - search  # make sure the search plugin is still enabled
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences